import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Image from "next/image";

export default function Examples() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-10 px-4 text-center md:px-6">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
                Example Icons
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Here are some icons generated by VectoAI. Click to see the
                magic.
              </p>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
              <div className="flex flex-col items-center gap-2">
                <Image
                  alt="Icon"
                  className="aspect-square overflow-hidden rounded-lg object-cover object-center"
                  height="200"
                  src="/example1.png"
                  width="200"
                />
                <h3 className="text-lg font-bold">Rocket</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Icon for launching your app
                </p>
              </div>
              <div className="flex flex-col items-center gap-2">
                <Image
                  alt="Icon"
                  className="aspect-square overflow-hidden rounded-lg object-cover object-center"
                  height="200"
                  src="/example1.png"
                  width="200"
                />
                <h3 className="text-lg font-bold">Coffee</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Icon for your morning brew
                </p>
              </div>
              <div className="flex flex-col items-center gap-2">
                <Image
                  alt="Icon"
                  className="aspect-square overflow-hidden rounded-lg object-cover object-center"
                  height="200"
                  src="/example1.png"
                  width="200"
                />
                <h3 className="text-lg font-bold">Umbrella</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Icon for rainy days
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
